# Data Manipulation and Analysis with Pandas
- Data Manipulation and analysis are key tasks in any data science or data analysis project.
- Pandas provides a wide range of functions for data manipulation and analysis, making it esier to clean, transform, and extract insights from data.
- In this lesson, we will cover various data mainpulation and analysis techniques using pandas.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Sales_data.csv")
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658.0,7,Electronics,Electronic Games,COD
1,B-26055,5729,64.0,14,Furniture,Chairs,EMI
2,B-25955,2927,146.0,8,Furniture,Bookcases,EMI
3,B-26093,2847,NaN,8,Electronics,Printers,Credit Card
4,B-25602,2617,NaN,4,Electronics,Phones,Credit Card

In [3]:
df.tail()

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7    -3.0         2     Clothing  Hankerchief         COD
1496  B-25757    3151   -35.0         7     Clothing     Trousers         EMI
1497  B-25973    4141  1698.0        13  Electronics     Printers         COD
1498  B-25698       7    -2.0         1     Clothing  Hankerchief         COD
1499  B-25993    4363   305.0         5    Furniture       Tables         EMI

In [4]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          3
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [5]:
df.describe()

            Amount       Profit     Quantity
count  1500.000000  1497.000000  1500.000000
mean    291.847333    23.281897     3.743333
std     461.924620   165.137159     2.184942
min       4.000000 -1981.000000     1.000000
25%      47.750000   -12.000000     2.000000
50%     122.000000     8.000000     3.000000
75%     326.250000    38.000000     5.000000
max    5729.000000  1864.000000    14.000000

In [6]:
df_fill = df.fillna(df["Profit"].mean())
df_fill.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658.000000,7,Electronics,Electronic Games,COD
1,B-26055,5729,64.000000,14,Furniture,Chairs,EMI
2,B-25955,2927,146.000000,8,Furniture,Bookcases,EMI
3,B-26093,2847,23.281897,8,Electronics,Printers,Credit Card
4,B-25602,2617,23.281897,4,Electronics,Phones,Credit Card

In [7]:
df["New_Amount"] = df["Amount"].apply(lambda x:x*2)
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,New_Amount
0,B-25681,1096,658.0,7,Electronics,Electronic Games,COD,2192
1,B-26055,5729,64.0,14,Furniture,Chairs,EMI,11458
2,B-25955,2927,146.0,8,Furniture,Bookcases,EMI,5854
3,B-26093,2847,NaN,8,Electronics,Printers,Credit Card,5694
4,B-25602,2617,NaN,4,Electronics,Phones,Credit Card,5234

## Data Aggregatting And Grouping

In [8]:
group_by_Cate = df.groupby('Category')['Profit'].mean()
group_by_Cate.head()

Category
Clothing       13.795359
Electronics    36.924837
Furniture      43.111111
Name: Profit, dtype: float64

In [9]:
# Group by using 2 Categorical Columns
group_by_cate_2 = df.groupby(['Category', 'PaymentMode'])['Quantity'].sum()
group_by_cate_2

Category     PaymentMode
Clothing     COD            1588
             Credit Card     378
             Debit Card      465
             EMI             316
             UPI             769
Electronics  COD             475
             Credit Card     172
             Debit Card      154
             EMI             154
             UPI             199
Furniture    COD             393
             Credit Card     122
             Debit Card      122
             EMI             119
             UPI             189
Name: Quantity, dtype: int64

## Aggregate multiple functions

In [ ]:
#16.36
grouped_agg = df.groupby("Category")['Profit'].agg(['mean', 'sum', 'count'])
grouped_agg

                  mean      sum  count
Category
Clothing     13.795359  13078.0    948
Electronics  36.924837  11299.0    306
Furniture    43.111111  10476.0    243

## Merging and joining DataFrame

In [24]:
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [25]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [26]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

## Merge DataFrame on the 'Key' Columns

In [27]:
df_merged = pd.merge(df1, df2, on='Key', how='inner')
df_merged

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [34]:
df1.merge(df2, on='Key', how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [35]:
df1.merge(df2, on='Key', how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [36]:
df1.merge(df2, on='Key', how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0