# Reading Data From Different Sources

In [1]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email":"james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2": "Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [2]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [3]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [4]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [16]:
# 4.35
df = pd.read_csv("red_wine_quality.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

### Reading dataset from HTML Page

In [19]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\rushi\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [33]:
urls = "https://www.fdic.gov/bank/individual/failed/banklist.html"
df1 = pd.read_html(urls)
df1

[                               Bank Name               City         State  \
 0                   Pulaski Savings Bank            Chicago      Illinois
 1     The First National Bank of Lindsay            Lindsay      Oklahoma
 2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania
 3                          Citizens Bank           Sac City          Iowa
 4               Heartland Tri-State Bank            Elkhart        Kansas
 5                    First Republic Bank      San Francisco    California
 6                         Signature Bank           New York      New York
 7                    Silicon Valley Bank        Santa Clara    California
 8                      Almena State Bank             Almena        Kansas
 9             First City Bank of Florida  Fort Walton Beach       Florida

     Cert                Acquiring Institution      Closing Date  \
 0  28611                      Millennium Bank  January 17, 2025
 1   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
 2  27332    Fulton Bank, National Association    April 26, 2024
 3   8758            Iowa Trust & Savings Bank  November 3, 2023
 4  25851               Dream First Bank, N.A.     July 28, 2023
 5  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
 6  57053                  Flagstar Bank, N.A.    March 12, 2023
 7  24735  First Citizens Bank & Trust Company    March 10, 2023
 8  15426                          Equity Bank  October 23, 2020
 9  16748            United Fidelity Bank, fsb  October 16, 2020

    Fund  Sort ascending
 0                 10548
 1                 10547
 2                 10546
 3                 10545
 4                 10544
 5                 10543
 6                 10540
 7                 10539
 8                 10538
 9                 10537  ]

In [38]:
df1[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
1,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,"First Bank & Trust Co., Duncan, OK","October 18, 2024",10547
2,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
3,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
4,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544

## Reading Wikipedia

In [46]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
df = pd.read_html(url, match="Country")
df

[     Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns]]

In [53]:
df[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [47]:
df_convert = pd.DataFrame(df[0])

In [48]:
df_convert.head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

## Reading Data with Excel Sheet xlsx

In [58]:
df_xlsx = pd.read_excel("sample_data.xlsx",sheet_name="Sheet1")
df_xlsx.head()

        Name  Age
0  Rushikesh   25
1     khushi   26
2       ram    20
3      sham    21

In [59]:
df_xlsx.describe()

            Age
count   4.00000
mean   23.00000
std     2.94392
min    20.00000
25%    20.75000
50%    23.00000
75%    25.25000
max    26.00000

In [60]:
df_xlsx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

## Converting df to Pickle File

In [61]:
df_xlsx.to_pickle('df_excel_pickle')

In [62]:
pickle_read = pd.read_pickle("df_excel_pickle")

In [63]:
pickle_read.head()

        Name  Age
0  Rushikesh   25
1     khushi   26
2       ram    20
3      sham    21

In [64]:
pickle_read.Name

0    Rushikesh
1       khushi
2         ram
3        sham
Name: Name, dtype: object